CREATE TABLE IF NOT EXISTS zone (
  zone_name TEXT NOT NULL PRIMARY KEY,
  setpoint REAL NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sensor (
  sensor_name TEXT NOT NULL PRIMARY KEY,
  value REAL NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS controller (
  name TEXT NOT NULL PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);