// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Controller struct {
	Name      string
	Value     string
	UpdatedAt sql.NullTime
}

type Sensor struct {
	SensorName string
	Value      float64
	UpdatedAt  sql.NullTime
}

type Zone struct {
	ZoneName  string
	Setpoint  float64
	UpdatedAt sql.NullTime
}
